build:
  environment:
    php: '7.0.8'

  tests:
    override:
      -
        command: 'phpunit --coverage-clover=clover.xml --bootstrap=tests/bootstrap.php tests/HookMeUp'
        coverage:
          file: 'clover.xml'
          format: 'clover'

# language: php

# tests: true
